#!/bin/bash
# List of files with their relative paths
FILES=(
 "app/page.js"
 "app/layout.js"
 "app/prod/[id]/page.js"
 "app/dashboard/page.js"
 "app/collections/[slug]/page.js"
 "app/api/CORE/"
 "components/"
 # "components/Scroll.js"
 # "components/LayoutWrapper.js"
 # "components/Top.js"
 # "components/Bottom.js"
 "app/globals.css"
 "app/page.module.css"
 "vStore/"
 "lib/"
  )
echo "Running: mcp"
printf "%s\n" "${FILES[@]}"
mcp "${FILES[@]}" > relevant_code.h

