//===== app/page.js =====
"use client";
import Image from "next/image";
import styles from "./page.module.css";
import { useState, useEffect, useRef } from "react";
import Scroll from "../components/Scroll";
import { carouselItems } from "../vStore/inventory";
export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <div className="image-container">
          <img src="https://co.silviatcherassi.com/cdn/shop/files/1402-3_1.jpg?v=1775769358&width=1500" />
          <img src="https://co.silviatcherassi.com/cdn/shop/files/2_f3b3831b-f41c-4f32-8a48-d5b3c045bac4.jpg?v=1775754993&width=1500" />
          <img src="https://co.silviatcherassi.com/cdn/shop/files/SPRING_2026_-_HERO_IMAGES_13_b2600db3-62f4-4632-b8e2-b433de7b77ee.jpg?v=1775489708&width=1500" />
          <img src="https://co.silviatcherassi.com/cdn/shop/files/SPRING_2026_-_HERO_IMAGES_19_e3e6e248-ee80-432f-a4be-114ceebf414b.jpg?v=1775489710&width=832" />
        </div>
        {/* <Image */}
        {/*   className={styles.logo} */}
        {/*   src="/next.svg" */}
        {/*   alt="Next.js logo" */}
        {/*   width={100} */}
        {/*   height={20} */}
        {/*   priority */}
        {/* /> */}
        <Scroll carouselItems={carouselItems} />
        <div className="image-container">
          <img src="https://co.silviatcherassi.com/cdn/shop/files/ST_d8f2e597-969e-4663-a915-a59d6f3d51c1.png?v=1759248174&width=1500" />
          <img src="https://co.silviatcherassi.com/cdn/shop/files/Sofia_Tennis_Bag.jpg?v=1775766367&width=1500" />
        </div>
        <div className={styles.ctas}>
          <a
            className={styles.primary}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className={styles.logo}
              src="/vercel.svg"
              alt="Vercel logomark"
              width={16}
              height={16}
            />
            Deploy Now
          </a>
          <a
            className={styles.secondary}
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Documentation
          </a>
        </div>
      </main>
    </div>
  );
}
//===== app/layout.js =====
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Top from "../components/Top.js";
import Bottom from "../components/Bottom.js";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <Top />
      <body>{children}</body>
      <Bottom />
    </html>
  );
}
//===== app/prod/[id]/page.js =====
"use client";
import { useParams } from "next/navigation";
import Scroll from "../../../components/Scroll";
import { carouselItems, getItemById } from "../../../vStore/inventory";
export default function Page() {
  const params = useParams();
  const id = Array.isArray(params.id) ? params.id[0] : params.id;
  const item = getItemById(id);
  return (
    <>
      <div style={{ display: "flex" }}>
        <div style={{ maxWidth: "50vw", overflow: "hidden" }}>
          {item.src && (
            <img style={{ width: "100%" }} src={item.src} alt={item.name} />
          )}
        </div>
        <div>
          <div style={{ minWidth: "50vw", padding: "40px 100px" }}>
            <h1>{item.name}</h1>
            <div>$2.100.000,00 COP </div>
            <div>
              {`Seleccionar Talla : XS Guía de
            Tallas`}
            </div>
            <button
              style={{
                padding: 20,
                width: "100%",
                background: "silver",
                marginTop: 60,
                marginBottom: 60,
              }}
            >
              Agregar al Carrito
            </button>
            <div className="detalles">
              <div>DETALLES</div>
              <div>ENVIOS Y DEVOLUCIONES</div>
            </div>
          </div>
        </div>
      </div>
      <div style={{ padding: 40 }}>You may also like</div>
      <Scroll carouselItems={carouselItems} />
    </>
  );
}
//===== components/Scroll.js =====
"use client";
import { useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
export default function Scroll({ carouselItems }) {
  const scrollRef = useRef(null);
  const router = useRouter();
  const dragRef = useRef({
    isDown: false,
    moved: false,
    startX: 0,
    scrollLeft: 0,
    pointerId: null,
    target: null,
  });
  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    const endDrag = () => {
      const { pointerId, moved, target } = dragRef.current;
      dragRef.current.isDown = false;
      if (pointerId !== null && el.hasPointerCapture?.(pointerId)) {
        el.releasePointerCapture(pointerId);
      }
      dragRef.current.pointerId = null;
      if (!moved && target) {
        const itemEl = target.closest("[data-item-id]");
        if (itemEl) {
          router.push(`/prod/${itemEl.dataset.itemId}`);
        }
      }
      dragRef.current.moved = false;
      dragRef.current.target = null;
    };
    const onPointerDown = (e) => {
      dragRef.current.isDown = true;
      dragRef.current.moved = false;
      dragRef.current.startX = e.clientX;
      dragRef.current.scrollLeft = el.scrollLeft;
      dragRef.current.pointerId = e.pointerId;
      dragRef.current.target = e.target;
      el.setPointerCapture(e.pointerId);
    };
    const onPointerMove = (e) => {
      if (!dragRef.current.isDown) return;
      const dx = e.clientX - dragRef.current.startX;
      if (Math.abs(dx) > 5) dragRef.current.moved = true;
      el.scrollLeft = dragRef.current.scrollLeft - dx;
    };
    el.addEventListener("pointerdown", onPointerDown);
    el.addEventListener("pointermove", onPointerMove);
    el.addEventListener("pointerup", endDrag);
    el.addEventListener("pointercancel", endDrag);
    el.addEventListener("lostpointercapture", endDrag);
    return () => {
      el.removeEventListener("pointerdown", onPointerDown);
      el.removeEventListener("pointermove", onPointerMove);
      el.removeEventListener("pointerup", endDrag);
      el.removeEventListener("pointercancel", endDrag);
      el.removeEventListener("lostpointercapture", endDrag);
    };
  }, []);
  return (
    <div
      ref={scrollRef}
      style={{
        overflowX: "scroll",
        maxWidth: "100%",
        cursor: "grab",
        userSelect: "none",
        touchAction: "pan-y",
      }}
    >
      <div style={{ display: "flex" }}>
        {carouselItems.map((item) => (
          <div
            key={item.id}
            data-item-id={item.id}
            style={{ overflow: "hidden", minWidth: "300px", cursor: "pointer" }}
          >
            <div className="carousel-img-wrapper">
              <img
                className="carousel-img"
                style={{
                  maxHeight: "300px",
                  minHeight: "300px",
                  pointerEvents: "none",
                }}
                src={item.src}
                alt={item.name}
              />
            </div>
            <div style={{ padding: 20, pointerEvents: "none" }}>
              {item.name}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
//===== components/Top.js =====
"use client";
import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
const menuItems = ["Comprar", "Colecciones", "Novias", "Más", "Boutiques"];
export default function Top() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isCartOpen, setIsCartOpen] = useState(false);
  return (
    <>
      <div
        style={{
          border: "",
          padding: 15,
          display: "flex",
          alignIems: "center",
          position: "sticky",
          top: 0,
          width: "100%",
          background: "rgba(127,127,127,0.62)",
        }}
      >
        <button onClick={() => setIsMenuOpen(!isMenuOpen)}>Menu</button>
        <b
          style={{ flex: 1, textAlign: "center", cursor: "pointer" }}
          onClick={() => router.push("/")}
        >
          ASHERALEPH
        </b>
        <button onClick={() => setIsCartOpen(!isCartOpen)}>Carrito</button>
      </div>
      <div
        style={{
          display: isMenuOpen ? "flex" : "none",
          flexDirection: "column",
          flex: 1,
          minHeight: "100vh",
          minWidth: "100%",
        }}
      >
        {menuItems.map((item) => (
          <div style={{ padding: 10 }} key={item}>
            {item}
          </div>
        ))}
      </div>
    </>
  );
}
//===== components/Bottom.js =====
export default function Bottom() {
  return (
    <div style={{ display: "flex", gap: 60, marginTop: 100, padding: 20 }}>
      <div>
        <h4>Relaciones con clientes</h4> <div>Contacto</div> <div>Atelier</div>{" "}
        <div>Colecciones</div>
      </div>{" "}
      <div>
        <h4>Legal</h4>
        <div>Términos Y Condiciones</div> <div>Compras En Línea</div>{" "}
        <div>Política de Privacidad</div>{" "}
        <div>Términos Y Condiciones De Uso</div>{" "}
        <div>Declaración de Accesibilidad</div>{" "}
        <div>Opciones de Accessibilidad</div>
      </div>
      <div>
        <h4>Únete a la conversación</h4> <div>Facebook</div>
        <div>Instagram</div> <div>Pinterest</div> <div>Tiktok</div>
      </div>
    </div>
  );
}
