//===== app/page.js =====
// app/page.js
"use client";
import { useEffect, useRef } from "react";
import styles from "./page.module.css";
import Link from "next/link";
import Scroll from "../components/Scroll";
import { useAssets } from "../vStore/CORE/assets";
const LABEL_H = 46;
const MARGIN = 16;
export default function Home() {
  const { products, collections } = useAssets(); // <-- reactive data
  const cardRefs = useRef([]);
  const labelRefs = useRef([]);
  useEffect(() => {
    const update = () => {
      const vh = window.innerHeight;
      cardRefs.current.forEach((card, i) => {
        const label = labelRefs.current[i];
        if (!card || !label) return;
        const rect = card.getBoundingClientRect();
        if (rect.bottom > vh && rect.top < vh) {
          label.style.top = `${vh - rect.top - LABEL_H - MARGIN}px`;
          label.style.bottom = "auto";
        } else {
          label.style.top = "";
          label.style.bottom = `${MARGIN}px`;
        }
      });
    };
    update();
    window.addEventListener("scroll", update, { passive: true });
    window.addEventListener("resize", update);
    return () => {
      window.removeEventListener("scroll", update);
      window.removeEventListener("resize", update);
    };
  }, []);
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <div
          style={{
            width: "100%",
            padding: 5,
            position: "sticky",
            top: "var(--topbar-height, 0px)",
            zIndex: 99,
            background: "rgba(127,127,127,0.72)",
            backdropFilter: "blur(7px)",
            boxShadow: "0 4px 24px rgba(0,0,0,0.35)",
            textShadow: "0 1px 4px rgba(0,0,0,0.45)",
          }}
        >
          Colecciones
        </div>
        <section className="collectionGrid">
          {collections.map((item, i) => (
            <div
              key={item._id}
              ref={(el) => (cardRefs.current[i] = el)}
              className="collectionCard"
            >
              <Link
                href={item.href}
                style={{ display: "block", width: "100%", height: "100%" }}
              >
                <img
                  src={item.src}
                  alt={item.name || item.title}
                  className="collectionImage"
                />
              </Link>
              <div
                ref={(el) => (labelRefs.current[i] = el)}
                className="collectionLabel"
              >
                {item.name || item.title}
              </div>
            </div>
          ))}
        </section>
        <div
          style={{
            width: "100%",
            padding: 5,
            position: "sticky",
            top: "var(--topbar-height, 0px)",
            zIndex: 99,
            background: "rgba(127,127,127,0.72)",
            backdropFilter: "blur(7px)",
            boxShadow: "0 4px 24px rgba(0,0,0,0.35)",
            textShadow: "0 1px 4px rgba(0,0,0,0.45)",
          }}
        >
          Comprar
        </div>
        <Scroll carouselItems={products} />
      </main>
      <style jsx global>{`
        /* existing styles unchanged */
        .collectionGrid {
          display: grid;
          grid-template-columns: repeat(2, minmax(0, 1fr));
          gap: 0;
          width: 100%;
        }
        @media (max-width: 768px) {
          .collectionGrid {
            grid-template-columns: 1fr;
          }
        }
        .collectionCard {
          position: relative;
          display: block;
          overflow: hidden;
          cursor: pointer;
          aspect-ratio: 4 / 5;
          line-height: 0;
        }
        .collectionLabel {
          position: absolute;
          left: 16px;
          bottom: 16px;
          width: fit-content;
          padding: 8px 14px;
          background: rgba(20, 20, 20, 0.62);
          color: #fff;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          font-size: 12px;
          line-height: normal;
          pointer-events: none;
        }
        .collectionImage {
          width: 100%;
          height: 100%;
          object-fit: cover;
          display: block;
          transition: transform 350ms ease;
        }
        .collectionCard:hover .collectionImage {
          transform: scale(1.03);
        }
      `}</style>
    </div>
  );
}
//===== app/layout.js =====
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "../components/LayoutWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
//===== app/prod/[id]/page.js =====
"use client";
import { useParams } from "next/navigation";
import { useState } from "react";
import { useAssets, getAsset } from "../../../vStore/CORE/assets";
import { useCart } from "../../../vStore/cartStore";
import Scroll from "../../../components/Scroll";
export default function ProductPage() {
  const params = useParams();
  const id = Array.isArray(params.id) ? params.id[0] : params.id;
  const { products } = useAssets();
  const product = getAsset("products", id);
  const { addItem } = useCart();
  const [quantity, setQuantity] = useState(1);
  if (!product) return <div>Producto no encontrado</div>;
  const handleAddToCart = () => {
    addItem(product, null, quantity);
    alert(`Añadido al carrito: ${product.name} x${quantity}`);
  };
  const fmtPrice = (price) =>
    new Intl.NumberFormat("es-CO", {
      style: "currency",
      currency: "COP",
      maximumFractionDigits: 0,
    }).format(price);
  return (
    <>
      <div style={{ display: "flex", flexWrap: "wrap" }}>
        <div style={{ minWidth: 500, flex: 1, overflow: "hidden" }}>
          {product.src && (
            <img
              style={{ width: "100%" }}
              src={product.src}
              alt={product.name}
            />
          )}
        </div>
        <div style={{ flex: 1, minWidth: 500 }}>
          <div style={{ padding: "40px 100px" }}>
            <h1>{product.name}</h1>
            <div>{fmtPrice(product.price)}</div>
            <div style={{ marginTop: 20 }}>
              <label>Cantidad: </label>
              <input
                type="number"
                min="1"
                value={quantity}
                onChange={(e) =>
                  setQuantity(Math.max(1, parseInt(e.target.value) || 1))
                }
                style={{ width: 60, marginLeft: 8, padding: 4 }}
              />
            </div>
            <button
              onClick={handleAddToCart}
              style={{
                borderRadius: 5,
                padding: 20,
                width: "100%",
                background: "rgba(127,127,127,0.62)",
                marginTop: 60,
                marginBottom: 60,
                cursor: "pointer",
                border: "none",
                fontSize: 16,
              }}
            >
              Agregar al Carrito
            </button>
            <div className="detalles">
              <div>DETALLES</div>
              <div>ENVIOS Y DEVOLUCIONES</div>
            </div>
          </div>
        </div>
      </div>
      <div style={{ padding: 40 }}>You may also like</div>
      <Scroll carouselItems={products} />
    </>
  );
}
//===== app/dashboard/page.js =====
"use client";
import { useState } from "react";
import {
  useAssets,
  addProduct,
  updateProduct,
  deleteProduct,
  addCollection,
  updateCollection,
  deleteCollection,
  assignCollection,
} from "../../vStore/CORE/assets";
export default function AdminDashboard() {
  const { products, collections } = useAssets();
  const [newProductName, setNewProductName] = useState("");
  const [newProductPrice, setNewProductPrice] = useState("");
  const [newProductSrc, setNewProductSrc] = useState("");
  const [newCollectionName, setNewCollectionName] = useState("");
  const handleAddProduct = () => {
    if (!newProductName) return;
    addProduct({
      id: Date.now().toString(),
      name: newProductName,
      price: parseFloat(newProductPrice) || 0,
      src: newProductSrc || null,
      variants: [],
      collectionId: null,
    });
    setNewProductName("");
    setNewProductPrice("");
    setNewProductSrc("");
  };
  const handleAddCollection = () => {
    if (!newCollectionName) return;
    addCollection({
      id: Date.now().toString(),
      name: newCollectionName,
      href: `/collections/${newCollectionName.toLowerCase().replace(/\s/g, "-")}`,
      src: "",
    });
    setNewCollectionName("");
  };
  return (
    <div
      style={{
        padding: "2rem",
        fontFamily: "sans-serif",
        maxWidth: 1200,
        margin: "0 auto",
      }}
    >
      <h1>Dashboard – Productos y Colecciones</h1>
      <div style={{ display: "flex", gap: "2rem", flexWrap: "wrap" }}>
        {/* Products section */}
        <div style={{ flex: 2, minWidth: 300 }}>
          <h2>Productos</h2>
          <div
            style={{
              marginBottom: "1rem",
              border: "1px solid #ccc",
              padding: "1rem",
              borderRadius: 8,
            }}
          >
            <h3>➕ Agregar producto</h3>
            <input
              type="text"
              placeholder="Nombre"
              value={newProductName}
              onChange={(e) => setNewProductName(e.target.value)}
              style={{
                display: "block",
                marginBottom: 8,
                width: "100%",
                padding: 6,
              }}
            />
            <input
              type="number"
              placeholder="Precio (COP)"
              value={newProductPrice}
              onChange={(e) => setNewProductPrice(e.target.value)}
              style={{
                display: "block",
                marginBottom: 8,
                width: "100%",
                padding: 6,
              }}
            />
            <input
              type="text"
              placeholder="URL de imagen"
              value={newProductSrc}
              onChange={(e) => setNewProductSrc(e.target.value)}
              style={{
                display: "block",
                marginBottom: 8,
                width: "100%",
                padding: 6,
              }}
            />
            <button
              onClick={handleAddProduct}
              style={{
                background: "#0070f3",
                color: "white",
                padding: "6px 12px",
                border: "none",
                borderRadius: 4,
              }}
            >
              Guardar producto
            </button>
          </div>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr>
                <th
                  style={{
                    textAlign: "left",
                    borderBottom: "1px solid #ddd",
                    padding: 8,
                  }}
                >
                  Nombre
                </th>
                <th
                  style={{
                    textAlign: "left",
                    borderBottom: "1px solid #ddd",
                    padding: 8,
                  }}
                >
                  Precio
                </th>
                <th
                  style={{
                    textAlign: "left",
                    borderBottom: "1px solid #ddd",
                    padding: 8,
                  }}
                >
                  Colección
                </th>
                <th
                  style={{
                    textAlign: "left",
                    borderBottom: "1px solid #ddd",
                    padding: 8,
                  }}
                >
                  Acciones
                </th>
              </tr>
            </thead>
            <tbody>
              {products.map((product) => (
                <tr key={product._id}>
                  <td style={{ padding: 8 }}>{product.name}</td>
                  <td style={{ padding: 8 }}>
                    ${product.price?.toLocaleString("es-CO")}
                  </td>
                  <td style={{ padding: 8 }}>
                    <select
                      value={product.collectionId || ""}
                      onChange={(e) =>
                        assignCollection(product._id, e.target.value || null)
                      }
                    >
                      <option value="">-- Sin colección --</option>
                      {collections.map((col) => (
                        <option key={col._id} value={col._id}>
                          {col.name}
                        </option>
                      ))}
                    </select>
                  </td>
                  <td style={{ padding: 8 }}>
                    <button
                      onClick={() => deleteProduct(product._id)}
                      style={{
                        background: "#dc2626",
                        color: "white",
                        border: "none",
                        padding: "4px 8px",
                        borderRadius: 4,
                      }}
                    >
                      Eliminar
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {/* Collections section */}
        <div style={{ flex: 1, minWidth: 250 }}>
          <h2>Colecciones</h2>
          <div
            style={{
              marginBottom: "1rem",
              border: "1px solid #ccc",
              padding: "1rem",
              borderRadius: 8,
            }}
          >
            <h3>➕ Agregar colección</h3>
            <input
              type="text"
              placeholder="Nombre de colección"
              value={newCollectionName}
              onChange={(e) => setNewCollectionName(e.target.value)}
              style={{
                display: "block",
                marginBottom: 8,
                width: "100%",
                padding: 6,
              }}
            />
            <button
              onClick={handleAddCollection}
              style={{
                background: "#0070f3",
                color: "white",
                padding: "6px 12px",
                border: "none",
                borderRadius: 4,
              }}
            >
              Guardar colección
            </button>
          </div>
          <ul style={{ listStyle: "none", padding: 0 }}>
            {collections.map((col) => (
              <li
                key={col._id}
                style={{
                  borderBottom: "1px solid #eee",
                  padding: "8px 0",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <span>{col.name}</span>
                <button
                  onClick={() => deleteCollection(col._id)}
                  style={{
                    background: "#dc2626",
                    color: "white",
                    border: "none",
                    padding: "2px 8px",
                    borderRadius: 4,
                  }}
                >
                  Eliminar
                </button>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}
//===== app/collections/[slug]/page.js =====
// app/collections/[slug]/page.js
"use client";
import { useMemo } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useAssets } from "../../../vStore/CORE/assets";
const fmtPrice = (price) =>
  new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    maximumFractionDigits: 0,
  }).format(price);
export default function CollectionPage() {
  const { slug } = useParams();
  const { products } = useAssets(); // real products
  const title = Array.isArray(slug)
    ? slug[0]
    : slug
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");
  // Shuffle products once per render (for variety)
  const shuffledProducts = useMemo(() => {
    if (!products?.length) return [];
    const arr = [...products];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }, [products]);
  return (
    <>
      <h4
        style={{
          position: "sticky",
          top: "var(--topbar-height, 0px)",
          padding: 10,
          zIndex: 10,
          textAlign: "center",
          textTransform: "uppercase",
          fontWeight: 400,
          background: "rgba(127,127,127,0.72)",
          backdropFilter: "blur(14px)",
          boxShadow: "0 4px 24px rgba(0,0,0,0.35)",
          textShadow: "0 1px 4px rgba(0,0,0,0.45)",
        }}
      >
        {title}
      </h4>
      <div className="mosaicGrid">
        {shuffledProducts.map((product) => (
          <Link
            key={product._id}
            href={`/prod/${product._id}`}
            className="mosaicCard"
          >
            <div className="mosaicImgWrapper">
              {product.src ? (
                <img
                  src={product.src}
                  alt={product.name}
                  className="mosaicImg"
                />
              ) : (
                <div className="mosaicFallback" />
              )}
            </div>
            <div className="mosaicInfo">
              <span className="mosaicName">{product.name}</span>
              <span className="mosaicPrice">{fmtPrice(product.price)}</span>
            </div>
          </Link>
        ))}
      </div>
      <style jsx global>{`
        /* your existing mosaic styles – unchanged */
        .mosaicGrid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 2px;
        }
        @media (max-width: 900px) {
          .mosaicGrid {
            grid-template-columns: repeat(2, 1fr);
          }
        }
        @media (max-width: 500px) {
          .mosaicGrid {
            grid-template-columns: 1fr;
          }
        }
        .mosaicCard {
          display: flex;
          flex-direction: column;
          text-decoration: none;
          color: inherit;
          cursor: pointer;
        }
        .mosaicImgWrapper {
          width: 100%;
          aspect-ratio: 3 / 4;
          overflow: hidden;
          background: #e8e4df;
        }
        .mosaicImg {
          width: 100%;
          height: 100%;
          object-fit: cover;
          display: block;
          transition:
            transform 500ms ease,
            opacity 300ms ease;
        }
        .mosaicFallback {
          width: 100%;
          height: 100%;
          background: #e8e4df;
        }
        .mosaicCard:hover .mosaicImg {
          opacity: 0.9;
          transform: scale(1.03);
        }
        .mosaicInfo {
          display: flex;
          flex-direction: column;
          gap: 4px;
          padding: 12px 4px;
        }
        .mosaicName {
          font-size: 13px;
          letter-spacing: 0.06em;
          text-transform: uppercase;
        }
        .mosaicPrice {
          font-size: 12px;
          color: #666;
        }
      `}</style>
    </>
  );
}
//===== app/api/CORE/[...slug]/route.js =====
// app/api/core/[[...slug]]/route.js
import { NextResponse } from "next/server";
import {
  get,
  getAll,
  create,
  remove,
  update,
} from "@/lib/api/models/default.js";
import { ObjectId } from "mongodb";
// DYNAMIC IMPORT HELPER
const getDbConnection = async () => {
  try {
    const { connectToDatabase } = await import("@/lib/mongodb");
    return connectToDatabase();
  } catch (error) {
    console.error("Database connection failed:", error);
    throw new Error("Failed to connect to database");
  }
};
const debug = (label, obj) => {
  try {
    console.log(`[api/core] ${label}:`, JSON.stringify(obj));
  } catch {
    console.log(`[api/core] ${label}: (unserializable)`);
  }
};
export async function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
    },
  });
}
function badRequest(message) {
  return NextResponse.json({ error: message }, { status: 400 });
}
export async function POST(req, { params }) {
  const { slug = [] } = await params;
  const collection = slug[0];
  debug("incoming", { method: "POST", url: req.url, params: slug });
  if (!collection)
    return badRequest("Missing collection in slug. Example: /api/core/posts");
  let body;
  try {
    body = await req.json();
  } catch (err) {
    debug("invalid-json", { err: err?.message });
    return badRequest(
      "Invalid JSON body. Ensure Content-Type: application/json and valid JSON.",
    );
  }
  const data = body?.data ? { ...body.data } : { ...body };
  if (!data || Object.keys(data).length === 0) {
    return badRequest(
      "Missing `data` payload for POST. Provide JSON with `data` object or payload fields.",
    );
  }
  data.creation = {
    utc: new Date().toISOString(),
    by: body?.by ?? null,
  };
  try {
    const response = await create(collection, data);
    const asset = JSON.parse(
      JSON.stringify({ _id: response.insertedId, ...data }),
    );
    return NextResponse.json({ response, asset });
  } catch (err) {
    console.error("[api/core] create error:", err);
    return NextResponse.json(
      { error: "Create failed", details: err?.message },
      { status: 500 },
    );
  }
}
export async function GET(req, { params }) {
  const { slug = [] } = await params;
  const collection = slug[0];
  debug("incoming", { method: "GET", url: req.url, params: slug });
  if (!collection)
    return badRequest("Missing collection in slug. Example: /api/core/posts");
  const url = new URL(req.url);
  const query = Object.fromEntries(url.searchParams.entries());
  try {
    const response = Object.keys(query).length
      ? await get(collection, query)
      : await getAll(collection);
    return NextResponse.json({ response });
  } catch (err) {
    console.error("[api/core] get error:", err);
    return NextResponse.json(
      { error: "Get failed", details: err?.message },
      { status: 500 },
    );
  }
}
export async function DELETEold(req, { params }) {
  const { slug = [] } = await params;
  const collection = slug[0];
  debug("incoming", { method: "DELETE", url: req.url, params: slug });
  if (!collection)
    return badRequest("Missing collection in slug. Example: /api/core/posts");
  const url = new URL(req.url);
  let id = url.searchParams.get("id");
  if (!id) {
    try {
      const body = await req.json().catch(() => null);
      id = body?.id;
    } catch (err) {
      // ignore parse error, will trigger missing id below
    }
  }
  if (!id)
    return badRequest(
      "Missing id for DELETE. Provide ?id=... or JSON body { id: '...' }",
    );
  try {
    const response = await remove(collection, { id });
    return NextResponse.json({ response });
  } catch (err) {
    console.error("[api/core] delete error:", err);
    return NextResponse.json(
      { error: "Delete failed", details: err?.message },
      { status: 500 },
    );
  }
}
export async function DELETE(request, { params }) {
  try {
    // params.slug is array because of [...slug] catch-all
    const slugParts = params?.slug || [];
    if (slugParts.length === 0) {
      return new Response(
        JSON.stringify({ message: "Collection name is required" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        },
      );
    }
    const collection = slugParts[0]; // e.g. "heroes", "projects", "files"
    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");
    // You can also support body as fallback/alternative
    let bodyId;
    try {
      const body = await request.json().catch(() => ({}));
      bodyId = body.id || body._id;
    } catch {}
    const assetId = id || bodyId;
    if (!assetId) {
      return new Response(
        JSON.stringify({
          message: "Asset ID is required (use ?id=... or body {id})",
        }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        },
      );
    }
    const { db } = await getDbConnection();
    let objectId;
    try {
      objectId = new ObjectId(assetId);
    } catch (err) {
      return new Response(JSON.stringify({ message: "Invalid ID format" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }
    const result = await db.collection(collection).deleteOne({ _id: objectId });
    if (result.deletedCount === 0) {
      return new Response(JSON.stringify({ message: "Asset not found" }), {
        status: 404,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(
      JSON.stringify({ message: "Asset deleted successfully" }),
      {
        status: 200,
        headers: { "Content-Type": "application/json" },
      },
    );
  } catch (error) {
    console.error("DELETE error:", error);
    return new Response(
      JSON.stringify({
        message: "Error deleting asset",
        error: error.message,
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      },
    );
  }
}
export async function PUT() {
  return NextResponse.json(
    {
      error:
        "PUT operation needs the field pattern. Example: api/music/comments",
    },
    { status: 400 },
  );
}
export async function PATCH(req, { params }) {
  const { slug = [] } = await params;
  const collection = slug[0];
  if (!collection) {
    return NextResponse.json(
      { error: "Missing collection in slug for PATCH." },
      { status: 400 },
    );
  }
  let body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body for PATCH." },
      { status: 400 },
    );
  }
  const id = body?.id || body?._id;
  const data = body?.data;
  if (!id || !data) {
    return NextResponse.json(
      { error: "PATCH requires { id, data }." },
      { status: 400 },
    );
  }
  const response = await update(collection, id, data);
  return NextResponse.json({ response });
}
//===== components/Scroll.js =====
"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
export default function Scroll({ carouselItems = [] }) {
  const [mounted, setMounted] = useState(false);
  const scrollRef = useRef(null);
  const router = useRouter();
  const dragRef = useRef({
    isDown: false,
    moved: false,
    startX: 0,
    scrollLeft: 0,
    pointerId: null,
    target: null,
  });
  useEffect(() => {
    setMounted(true);
  }, []);
  useEffect(() => {
    if (!mounted) return;
    const el = scrollRef.current;
    if (!el) return;
    const endDrag = () => {
      const { pointerId, moved, target } = dragRef.current;
      dragRef.current.isDown = false;
      if (pointerId !== null && el.hasPointerCapture?.(pointerId)) {
        el.releasePointerCapture(pointerId);
      }
      dragRef.current.pointerId = null;
      if (!moved && target) {
        const itemEl = target.closest("[data-item-id]");
        if (itemEl) {
          router.push(`/prod/${itemEl.dataset.itemId}`);
        }
      }
      dragRef.current.moved = false;
      dragRef.current.target = null;
    };
    const onPointerDown = (e) => {
      dragRef.current.isDown = true;
      dragRef.current.moved = false;
      dragRef.current.startX = e.clientX;
      dragRef.current.scrollLeft = el.scrollLeft;
      dragRef.current.pointerId = e.pointerId;
      dragRef.current.target = e.target;
      el.setPointerCapture(e.pointerId);
    };
    const onPointerMove = (e) => {
      if (!dragRef.current.isDown) return;
      const dx = e.clientX - dragRef.current.startX;
      if (Math.abs(dx) > 5) {
        dragRef.current.moved = true;
      }
      el.scrollLeft = dragRef.current.scrollLeft - dx;
    };
    el.addEventListener("pointerdown", onPointerDown);
    el.addEventListener("pointermove", onPointerMove);
    el.addEventListener("pointerup", endDrag);
    el.addEventListener("pointercancel", endDrag);
    el.addEventListener("lostpointercapture", endDrag);
    return () => {
      el.removeEventListener("pointerdown", onPointerDown);
      el.removeEventListener("pointermove", onPointerMove);
      el.removeEventListener("pointerup", endDrag);
      el.removeEventListener("pointercancel", endDrag);
      el.removeEventListener("lostpointercapture", endDrag);
    };
  }, [mounted, router]);
  // Prevent hydration mismatch
  if (!mounted) {
    return null;
  }
  return (
    <div
      ref={scrollRef}
      style={{
        overflowX: "scroll",
        maxWidth: "100%",
        cursor: "grab",
        userSelect: "none",
        touchAction: "pan-y",
      }}
    >
      <div style={{ display: "flex" }}>
        {carouselItems.map((item) => (
          <div
            key={String(item._id)}
            data-item-id={item._id}
            style={{
              overflow: "hidden",
              minWidth: "300px",
              cursor: "pointer",
            }}
          >
            <div className="carousel-img-wrapper">
              <img
                className="carousel-img"
                style={{
                  maxHeight: "300px",
                  minHeight: "300px",
                  pointerEvents: "none",
                }}
                src={item.src}
                alt={item.name}
              />
            </div>
            <div style={{ padding: 20, pointerEvents: "none" }}>
              {item.name}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
//===== components/Cart.js =====
"use client";
import { useEffect, useMemo, useState } from "react";
import { useCart } from "../vStore/cartStore";
import { useAssets } from "../vStore/CORE/assets"; // changed import
const fmt = (n) =>
  new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    maximumFractionDigits: 0,
  }).format(n);
function CartItem({ item, product, onQty, onRemove }) {
  if (!product) return null;
  return (
    <div style={s.item}>
      <div style={s.thumb}>
        {product.src && (
          <img
            src={product.src}
            alt={product.name}
            style={{ width: "100%", height: "100%", objectFit: "cover" }}
          />
        )}
      </div>
      <div style={s.itemBody}>
        <div style={s.itemTop}>
          <span style={s.itemName}>{product.name}</span>
          <span style={s.itemPrice}>{fmt(item.price * item.qty)}</span>
        </div>
        {item.variant && <span style={s.itemVariant}>{item.variant}</span>}
        <div style={s.itemActions}>
          <div style={s.stepper}>
            <button
              style={s.stepBtn}
              onClick={() => onQty(item._id, item.variant, item.qty - 1)}
            >
              −
            </button>
            <span style={s.qty}>{item.qty}</span>
            <button
              style={s.stepBtn}
              onClick={() => onQty(item._id, item.variant, item.qty + 1)}
            >
              +
            </button>
          </div>
          <button
            style={s.removeBtn}
            onClick={() => onRemove(item._id, item.variant)}
          >
            Eliminar
          </button>
        </div>
      </div>
    </div>
  );
}
export default function CartOverlay() {
  const [open, setOpen] = useState(false);
  const [mounted, setMounted] = useState(false);
  const { items, count, subtotal, updateQty, removeItem } = useCart();
  const { products } = useAssets(); // changed hook
  useEffect(() => {
    setMounted(true);
  }, []);
  useEffect(() => {
    if (!open) return;
    const onKey = (e) => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);
  useEffect(() => {
    document.body.style.overflow = open ? "hidden" : "";
    return () => {
      document.body.style.overflow = "";
    };
  }, [open]);
  const productMap = useMemo(() => {
    const map = {};
    (products || []).forEach((p) => {
      map[p._id] = p; // use _id
    });
    return map;
  }, [products]);
  const sendWhatsAppOrder = () => {
    const customerPhone = window.prompt(
      "Por favor, ingresa tu número de teléfono (ej: 3001234567) para que podamos contactarte:",
      "",
    );
    if (!customerPhone) {
      alert("Necesitamos tu número de teléfono para procesar el pedido.");
      return;
    }
    const cleaned = customerPhone.replace(/\D/g, "");
    if (cleaned.length < 7) {
      alert(
        "Por favor ingresa un número de teléfono válido (mínimo 7 dígitos).",
      );
      return;
    }
    const sellerNumber = "573153410282";
    let message = "🛍️ *Nuevo Pedido*%0A%0A";
    message += `📞 *Teléfono del cliente:* ${cleaned}%0A%0A`;
    items.forEach((item, idx) => {
      const product = productMap[item._id]; // use _id
      if (!product) return;
      const variantText = item.variant ? ` (${item.variant})` : "";
      const itemPrice = fmt(item.price * item.qty);
      message += `${idx + 1}. ${product.name}${variantText} x${item.qty} → ${itemPrice}%0A`;
    });
    message += `%0A📦 *Subtotal:* ${fmt(subtotal)}%0A`;
    message += `🚚 *Envío e impuestos:* Calculados al finalizar%0A%0A`;
    message += `🔗 Gracias por tu compra.`;
    window.open(`https://wa.me/${sellerNumber}?text=${message}`, "_blank");
  };
  if (!mounted) return null;
  return (
    <>
      <button
        onClick={() => setOpen((v) => !v)}
        style={{ ...s.fab, ...(open ? s.fabOpen : {}) }}
        aria-label="Carrito"
      >
        {open ? (
          <span style={{ fontSize: 16, lineHeight: 1 }}>✕</span>
        ) : (
          <>
            <svg
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z" />
              <line x1="3" y1="6" x2="21" y2="6" />
              <path d="M16 10a4 4 0 01-8 0" />
            </svg>
            {count > 0 && <span style={s.fabBadge}>{count}</span>}
          </>
        )}
      </button>
      <div
        onClick={() => setOpen(false)}
        style={{
          ...s.backdrop,
          opacity: open ? 1 : 0,
          pointerEvents: open ? "auto" : "none",
        }}
      />
      <aside
        style={{
          ...s.drawer,
          transform: open ? "translateX(0)" : "translateX(100%)",
        }}
        role="dialog"
        aria-modal="true"
        aria-label="Carrito de compras"
      >
        <div style={s.head}>
          <span style={s.title}>🛍️ Carrito</span>
          {count > 0 && <span style={s.badge}>{count}</span>}
          <button
            style={s.closeBtn}
            onClick={() => setOpen(false)}
            aria-label="Cerrar"
          >
            ✕
          </button>
        </div>
        <div style={s.body}>
          {items.length === 0 ? (
            <div style={s.empty}>
              <svg
                width="38"
                height="38"
                viewBox="0 0 24 24"
                fill="none"
                stroke="rgba(127,127,127,0.5)"
                strokeWidth="1"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z" />
                <line x1="3" y1="6" x2="21" y2="6" />
              </svg>
              <p style={s.emptyText}>Tu carrito está vacío.</p>
            </div>
          ) : (
            items.map((item) => (
              <CartItem
                key={`${item._id || item.id}-${item.variant ?? "novariant"}`}
                item={item}
                product={productMap[item._id || item.id]} // also safe for old items
                onQty={updateQty}
                onRemove={removeItem}
              />
            ))
          )}
        </div>
        {items.length > 0 && (
          <div style={s.footer}>
            <div style={s.subtotalRow}>
              <span style={s.subtotalLabel}>Subtotal</span>
              <span style={s.subtotalValue}>{fmt(subtotal)}</span>
            </div>
            <p style={s.taxNote}>Envío e impuestos calculados al finalizar</p>
            <button style={s.checkoutBtn} onClick={sendWhatsAppOrder}>
              Finalizar Compra
            </button>
            <button style={s.continueBtn} onClick={() => setOpen(false)}>
              Seguir comprando
            </button>
          </div>
        )}
      </aside>
    </>
  );
}
// ---------- Styles ----------
const s = {
  fab: {
    position: "fixed",
    bottom: 28,
    right: 28,
    zIndex: 100000,
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "rgba(10,10,10,0.92)",
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "#ededed",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 24px rgba(0,0,0,0.4)",
    transition: "transform .2s ease, background .2s ease",
    textShadow: "none",
  },
  fabOpen: {
    background: "rgba(40,40,40,0.98)",
    transform: "scale(0.92)",
  },
  fabBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    minWidth: 16,
    height: 16,
    padding: "0 3px",
    background: "#ededed",
    color: "#111",
    borderRadius: 999,
    fontSize: 9,
    fontFamily: "var(--font-geist-mono)",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
    pointerEvents: "none",
  },
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 99998,
    background: "rgba(0,0,0,0.35)",
    backdropFilter: "blur(3px)",
    transition: "opacity .3s",
  },
  drawer: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: "min(420px, 100vw)",
    zIndex: 99999,
    background: "rgba(10,10,10,0.97)",
    backdropFilter: "blur(20px)",
    color: "#ededed",
    display: "flex",
    flexDirection: "column",
    transition: "transform .38s cubic-bezier(.32,.72,0,1)",
    borderLeft: "1px solid rgba(255,255,255,0.08)",
    fontFamily: "var(--font-geist-sans)",
  },
  head: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "18px 22px",
    borderBottom: "1px solid rgba(255,255,255,0.07)",
  },
  title: {
    flex: 1,
    fontSize: 14,
    fontWeight: 500,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#ededed",
  },
  badge: {
    fontFamily: "var(--font-geist-mono)",
    fontSize: 10,
    color: "rgba(200,200,200,0.7)",
    padding: "2px 6px",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 4,
  },
  closeBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "rgba(200,200,200,0.5)",
    fontSize: 14,
    padding: "2px 4px",
    lineHeight: 1,
    textShadow: "none",
  },
  body: { flex: 1, overflowY: "auto", padding: "0 22px" },
  item: {
    display: "flex",
    gap: 14,
    padding: "18px 0",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  thumb: {
    width: 68,
    height: 84,
    flexShrink: 0,
    background: "rgba(255,255,255,0.05)",
    borderRadius: 4,
    overflow: "hidden",
  },
  itemBody: { flex: 1, display: "flex", flexDirection: "column", gap: 4 },
  itemTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  itemName: {
    fontSize: 13,
    fontWeight: 400,
    letterSpacing: "0.04em",
    color: "#ededed",
    lineHeight: 1.35,
  },
  itemPrice: {
    fontFamily: "var(--font-geist-mono)",
    fontSize: 12,
    color: "#ededed",
    flexShrink: 0,
    marginLeft: 8,
  },
  itemVariant: {
    fontSize: 11,
    color: "rgba(200,200,200,0.45)",
    letterSpacing: "0.04em",
  },
  itemActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  stepper: {
    display: "flex",
    alignItems: "center",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 3,
    overflow: "hidden",
  },
  stepBtn: {
    width: 28,
    height: 26,
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    color: "rgba(200,200,200,0.6)",
    lineHeight: 1,
    textShadow: "none",
    padding: 0,
  },
  qty: {
    width: 26,
    textAlign: "center",
    fontFamily: "var(--font-geist-mono)",
    fontSize: 12,
    color: "#ededed",
    borderLeft: "1px solid rgba(255,255,255,0.12)",
    borderRight: "1px solid rgba(255,255,255,0.12)",
    lineHeight: "26px",
  },
  removeBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 10,
    color: "rgba(200,200,200,0.35)",
    textDecoration: "underline",
    padding: 0,
    letterSpacing: "0.04em",
    textShadow: "none",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    height: 260,
  },
  emptyText: {
    fontSize: 13,
    color: "rgba(200,200,200,0.35)",
    letterSpacing: "0.04em",
  },
  footer: {
    padding: "18px 22px",
    borderTop: "1px solid rgba(255,255,255,0.07)",
  },
  subtotalRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  subtotalLabel: {
    fontSize: 12,
    color: "rgba(200,200,200,0.5)",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  subtotalValue: {
    fontFamily: "var(--font-geist-mono)",
    fontSize: 15,
    fontWeight: 500,
    color: "#ededed",
  },
  taxNote: {
    fontSize: 10,
    color: "rgba(200,200,200,0.3)",
    marginBottom: 14,
    letterSpacing: "0.02em",
  },
  checkoutBtn: {
    width: "100%",
    height: 44,
    background: "#ededed",
    color: "#0a0a0a",
    border: "none",
    borderRadius: 3,
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    marginBottom: 8,
    textShadow: "none",
    fontFamily: "var(--font-geist-sans)",
  },
  continueBtn: {
    width: "100%",
    height: 38,
    background: "none",
    color: "rgba(200,200,200,0.45)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 3,
    fontSize: 11,
    cursor: "pointer",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    fontFamily: "var(--font-geist-sans)",
    textShadow: "none",
  },
};
//===== components/LayoutWrapper.js =====
// components/LayoutWrapper.js (updated)
"use client";
import { useEffect } from "react";
import { usePathname } from "next/navigation";
import Top from "./Top";
import Bottom from "./Bottom";
import CartOverlay from "./Cart";
import { initAssets } from "@/vStore/CORE/assets"; // new import
export default function LayoutWrapper({ children }) {
  const pathname = usePathname();
  const isDashboard = pathname?.includes("/dashboard");
  useEffect(() => {
    initAssets();
  }, []);
  return (
    <>
      {!isDashboard && <CartOverlay />}
      {!isDashboard && <Top />}
      {children}
      {!isDashboard && <Bottom />}
    </>
  );
}
//===== components/Top.js =====
"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
const leftItems = ["Comprar", "Colecciones", "Novias", "Más"];
const rightItems = ["🔎", "Carrito"];
export default function Top() {
  const router = useRouter();
  const topbarRef = useRef(null);
  const measureRef = useRef(null);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [activeItem, setActiveItem] = useState(null);
  const [mobileActiveItem, setMobileActiveItem] = useState(null);
  const [topbarHeight, setTopbarHeight] = useState(0);
  const [canInlineNav, setCanInlineNav] = useState(true);
  useEffect(() => {
    const updateLayout = () => {
      if (topbarRef.current) {
        const h = topbarRef.current.offsetHeight;
        setTopbarHeight(h);
        document.documentElement.style.setProperty("--topbar-height", `${h}px`);
      }
      if (measureRef.current && topbarRef.current) {
        const available = topbarRef.current.clientWidth;
        const needed = measureRef.current.scrollWidth + 24;
        setCanInlineNav(available >= needed);
      }
    };
    updateLayout();
    const ro = new ResizeObserver(updateLayout);
    if (topbarRef.current) ro.observe(topbarRef.current);
    window.addEventListener("resize", updateLayout);
    return () => {
      ro.disconnect();
      window.removeEventListener("resize", updateLayout);
    };
  }, []);
  useEffect(() => {
    if (canInlineNav) {
      setIsMenuOpen(false);
      setMobileActiveItem(null);
    }
    setActiveItem(null);
  }, [canInlineNav]);
  useEffect(() => {
    const handleScroll = () => {
      if (!canInlineNav && window.scrollY > 80) {
        setIsMenuOpen(false);
        setMobileActiveItem(null);
      }
      if (canInlineNav && window.scrollY > 80) {
        setActiveItem(null);
      }
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, [canInlineNav]);
  useEffect(() => {
    if (!activeItem) return;
    const handleClickOutside = (e) => {
      if (topbarRef.current && !topbarRef.current.contains(e.target)) {
        setActiveItem(null);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, [activeItem]);
  const handleLeftItemClick = (item) => {
    setActiveItem((prev) => (prev === item ? null : item));
  };
  const isDropdownOpen = canInlineNav && activeItem !== null;
  const isMobileSubOpen =
    !canInlineNav && isMenuOpen && mobileActiveItem !== null;
  return (
    <>
      <div
        ref={topbarRef}
        style={{
          position: "sticky",
          top: 0,
          zIndex: 2000,
          width: "100%",
          background: "rgba(72,72,72,0.62)",
          backdropFilter: "blur(14px)",
          boxShadow: "0 4px 24px rgba(0,0,0,0.35)",
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr auto 1fr",
            alignItems: "center",
            padding: "15px 20px",
            gap: 20,
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 22,
              minWidth: 0,
              overflow: "hidden",
              whiteSpace: "nowrap",
            }}
          >
            {canInlineNav ? (
              leftItems.map((item) => (
                <button
                  key={item}
                  className={`topLink${activeItem === item ? " topLinkActive" : ""}`}
                  type="button"
                  onClick={() => handleLeftItemClick(item)}
                >
                  {item}
                </button>
              ))
            ) : (
              <button
                className="topLink"
                type="button"
                onClick={() => {
                  setIsMenuOpen((v) => !v);
                  setMobileActiveItem(null);
                }}
              >
                Menu
              </button>
            )}
          </div>
          <b
            style={{
              textAlign: "center",
              cursor: "pointer",
              letterSpacing: "0.18em",
              fontWeight: 700,
              whiteSpace: "nowrap",
              textShadow: "0 1px 4px rgba(0,0,0,0.45)",
            }}
            onClick={() => {
              router.push("/");
              setActiveItem(null);
            }}
          >
            ASHERALEPH
          </b>
          <div
            style={{
              display: "flex",
              justifyContent: "flex-end",
              alignItems: "center",
              gap: 18,
              minWidth: 0,
              overflow: "hidden",
              whiteSpace: "nowrap",
            }}
          >
            {rightItems.map((item) => (
              <button key={item} className="topLink" type="button">
                {item}
              </button>
            ))}
          </div>
        </div>
        <div
          ref={measureRef}
          aria-hidden="true"
          style={{
            position: "absolute",
            visibility: "hidden",
            pointerEvents: "none",
            left: -99999,
            top: -99999,
            whiteSpace: "nowrap",
            display: "flex",
            alignItems: "center",
            gap: 18,
            padding: "15px 20px",
          }}
        >
          {leftItems.map((item) => (
            <span key={item} style={{ padding: "6px 0" }}>
              {item}
            </span>
          ))}
          <span style={{ letterSpacing: "0.18em", fontWeight: 700 }}>
            ASHERALEPH
          </span>
          {rightItems.map((item) => (
            <span key={item} style={{ padding: "6px 0" }}>
              {item}
            </span>
          ))}
        </div>
      </div>
      {/* Desktop dropdown */}
      <div
        style={{
          position: "fixed",
          top: Math.max(0, topbarHeight - 1),
          left: 0,
          right: 0,
          zIndex: 1500,
          background: "rgba(72,72,72,0.62)",
          backdropFilter: "blur(18px)",
          color: "#fff",
          overflow: "hidden",
          opacity: isDropdownOpen ? 1 : 0,
          transform: isDropdownOpen ? "translateY(0px)" : "translateY(-12px)",
          pointerEvents: isDropdownOpen ? "auto" : "none",
          transition: "opacity 0.28s ease, transform 0.28s ease",
          boxShadow: "0 14px 40px rgba(0,0,0,0.45)",
        }}
      >
        <div style={{ padding: "32px 40px 28px" }}>
          <h4
            style={{
              margin: 0,
              fontWeight: 600,
              fontSize: 20,
              letterSpacing: "0.08em",
              color: "#fff",
            }}
          >
            {activeItem}
          </h4>
        </div>
      </div>
      {/* Mobile dropdown */}
      {!canInlineNav && (
        <div
          style={{
            position: "fixed",
            top: Math.max(0, topbarHeight - 1),
            left: 0,
            right: 0,
            zIndex: 1500,
            background: "rgba(200,200,200,0.62)",
            backdropFilter: "blur(18px)",
            color: "#fff",
            overflow: "hidden",
            opacity: isMenuOpen ? 1 : 0,
            transform: isMenuOpen ? "translateY(0px)" : "translateY(-12px)",
            pointerEvents: isMenuOpen ? "auto" : "none",
            transition: "opacity 0.28s ease, transform 0.28s ease",
            boxShadow: "0 14px 40px rgba(0,0,0,0.45)",
          }}
        >
          {/* Sliding track — two panels side by side */}
          <div
            style={{
              display: "flex",
              width: "200%",
              transform: isMobileSubOpen
                ? "translateX(-50%)"
                : "translateX(0%)",
              transition: "transform 0.3s cubic-bezier(0.4,0,0.2,1)",
            }}
          >
            {/* Panel 1 — main list */}
            <div style={{ width: "50%", flexShrink: 0 }}>
              {leftItems.map((item) => (
                <button
                  key={item}
                  type="button"
                  className="menuItem menuItemMobile"
                  onClick={() => setMobileActiveItem(item)}
                >
                  <span>{item}</span>
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                    style={{ opacity: 0.5 }}
                  >
                    <path
                      d="M6 3l5 5-5 5"
                      stroke="currentColor"
                      strokeWidth="1.6"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </button>
              ))}
            </div>
            {/* Panel 2 — sub-menu */}
            <div style={{ width: "50%", flexShrink: 0 }}>
              {/* Back button */}
              <button
                type="button"
                className="menuItem menuItemMobile mobileBackBtn"
                onClick={() => setMobileActiveItem(null)}
              >
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 16 16"
                  fill="none"
                  style={{ opacity: 0.6 }}
                >
                  <path
                    d="M10 3L5 8l5 5"
                    stroke="currentColor"
                    strokeWidth="1.6"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
                <span style={{ opacity: 0.6, fontSize: 13 }}>Volver</span>
              </button>
              {/* Sub-menu title */}
              <div style={{ padding: "24px 20px 16px" }}>
                <h4
                  style={{
                    margin: 0,
                    fontWeight: 600,
                    fontSize: 20,
                    letterSpacing: "0.08em",
                    color: "#fff",
                  }}
                >
                  {mobileActiveItem}
                </h4>
              </div>
            </div>
          </div>
        </div>
      )}
      <style jsx global>{`
        .topLink {
          appearance: none;
          border: 0;
          background: transparent;
          color: inherit;
          font: inherit;
          font-size: 14px;
          cursor: pointer;
          padding: 6px 0;
          letter-spacing: 0.02em;
          transition:
            opacity 180ms ease,
            transform 180ms ease;
        }
        .topLink:hover {
          opacity: 0.72;
          transform: translateY(-1px);
        }
        .topLinkActive {
          opacity: 0.72;
          transform: translateY(-1px);
          text-decoration: underline;
          text-underline-offset: 4px;
        }
        .menuItem {
          appearance: none;
          border: 0;
          background: transparent;
          color: inherit;
          font: inherit;
          font-size: 18px;
          letter-spacing: 0.02em;
          cursor: pointer;
          text-align: left;
          width: 100%;
          display: flex;
          align-items: center;
          justify-content: space-between;
          transition:
            background-color 180ms ease,
            transform 180ms ease;
        }
        .menuItem:hover {
          background: rgba(255, 255, 255, 0.05);
        }
        .menuItemMobile {
          padding: 20px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.08);
        }
        .mobileBackBtn {
          justify-content: flex-start;
          gap: 8px;
          font-size: 14px;
        }
      `}</style>
    </>
  );
}
//===== components/Top_legacy.js =====
"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
const menuItems = ["Comprar", "Colecciones", "Novias", "Más", "Boutiques"];
export default function Top() {
  const router = useRouter();
  const topbarRef = useRef(null);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isCartOpen, setIsCartOpen] = useState(false);
  const [topbarHeight, setTopbarHeight] = useState(0);
  useEffect(() => {
    const updateHeight = () => {
      if (topbarRef.current) {
        setTopbarHeight(topbarRef.current.offsetHeight);
      }
    };
    updateHeight();
    window.addEventListener("resize", updateHeight);
    return () => {
      window.removeEventListener("resize", updateHeight);
    };
  }, []);
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 80 && isMenuOpen) {
        setIsMenuOpen(false);
      }
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, [isMenuOpen]);
  return (
    <>
      {/* TOPBAR */}
      <div
        ref={topbarRef}
        style={{
          position: "sticky",
          top: 0,
          zIndex: 2000,
          padding: "15px 20px",
          display: "flex",
          alignItems: "center",
          width: "100%",
          background: "rgba(0,0,0,0.72)",
          backdropFilter: "blur(14px)",
          color: "#fff",
          boxShadow: "0 4px 24px rgba(0,0,0,0.35)",
        }}
      >
        <button
          onClick={() => setIsMenuOpen((v) => !v)}
          style={{
            color: "inherit",
            fontWeight: 600,
          }}
        >
          Menu
        </button>
        <b
          style={{
            flex: 1,
            textAlign: "center",
            cursor: "pointer",
            letterSpacing: "0.08em",
            fontWeight: 700,
            textShadow: "0 1px 4px rgba(0,0,0,0.45)",
          }}
          onClick={() => router.push("/")}
        >
          ASHERALEPH
        </b>
        <button
          onClick={() => setIsCartOpen((v) => !v)}
          style={{
            color: "inherit",
            fontWeight: 600,
          }}
        >
          Carrito
        </button>
      </div>
      {/* MENU OVERLAY */}
      <div
        style={{
          position: "fixed",
          top: topbarHeight - 1,
          left: 0,
          right: 0,
          zIndex: 1500,
          background: "rgba(0,0,0,0.94)",
          backdropFilter: "blur(18px)",
          color: "#fff",
          overflow: "hidden",
          opacity: isMenuOpen ? 1 : 0,
          transform: isMenuOpen ? "translateY(0px)" : "translateY(-18px)",
          pointerEvents: isMenuOpen ? "auto" : "none",
          transition: "opacity 0.35s ease, transform 0.35s ease",
          boxShadow: "0 14px 40px rgba(0,0,0,0.45)",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "300px",
          }}
        >
          {menuItems.map((item) => (
            <div
              key={item}
              className="menuItem"
              onClick={() => setIsMenuOpen(false)}
            >
              {item}
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
//===== components/Bottom.js =====
export default function Bottom() {
  return (
    <>
      <div
        style={{
          width: "100%",
          padding: 5,
          position: "sticky",
          top: "var(--topbar-height, 0px)",
          zIndex: 99,
          background: "rgba(127,127,127,0.72)",
          backdropFilter: "blur(7px)",
          boxShadow: "0 4px 24px rgba(0,0,0,0.35)",
          textShadow: "0 1px 4px rgba(0,0,0,0.45)",
        }}
      >
        ASHERALEPH
      </div>
      <div className="image-container">
        <img src="https://co.silviatcherassi.com/cdn/shop/files/ST_d8f2e597-969e-4663-a915-a59d6f3d51c1.png?v=1759248174&width=1500" />
        <img src="https://co.silviatcherassi.com/cdn/shop/files/Sofia_Tennis_Bag.jpg?v=1775766367&width=1500" />
      </div>
      <div
        className="bottomBS"
        style={{ display: "flex", gap: 60, marginTop: 100, padding: 20 }}
      >
        <div>
          <h4>Relaciones con clientes</h4> <div>Contacto</div>{" "}
          <div>Atelier</div> <div>Colecciones</div>
        </div>{" "}
        <div>
          <h4>Legal</h4>
          <div>Términos Y Condiciones</div> <div>Compras En Línea</div>{" "}
          <div>Política de Privacidad</div>{" "}
          <div>Términos Y Condiciones De Uso</div>{" "}
          <div>Declaración de Accesibilidad</div>{" "}
          <div>Opciones de Accessibilidad</div>
        </div>
        <div>
          <h4>Únete a la conversación</h4> <div>Facebook</div>
          <div>Instagram</div> <div>Pinterest</div> <div>Tiktok</div>
        </div>
      </div>
    </>
  );
}
//===== app/globals.css =====
:root {
  --background: #ffffff;
  --foreground: #171717;
}
@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}
html {
  height: 100%;
}
html,
body {
  max-width: 100vw;
}
body {
  min-height: 100%;
  display: flex;
  flex-direction: column;
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
}
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}
a {
  color: inherit;
  text-decoration: none;
}
.image-container {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(550px, 1fr));
  width: 100vw;
}
.image-container img {
  width: 100%;
  max-width: 100vw;
  height: 100%;
  object-fit: cover;
}
.carousel-img {
  /* opacity: 0.6; */
}
.carousel-img-wrapper {
  overflow: hidden;
  max-height: 300px;
  min-height: 300px;
}
.carousel-img-wrapper img:hover {
  transform: scale(1.62);
}
.detalles {
  border-top: 1px solid silver;
  margin-top: 20px;
}
.detalles div {
  padding: 20px;
  border-bottom: 1px solid silver;
}
.detalles div:hover {
  background: silver;
  color: black;
}
.scroll {
  overflow-x: auto;
  scrollbar-width: thin;
  /* Firefox */
  scrollbar-color: rgba(100, 100, 100, 0.3) transparent;
}
.scroll::-webkit-scrollbar {
  height: 6px;
  /* thin horizontal bar */
}
.scroll::-webkit-scrollbar-track {
  background: transparent;
  /* invisible track */
}
.scroll::-webkit-scrollbar-thumb {
  background: rgba(0, 0, 0, 0.3);
  border-radius: 999px;
}
.scroll::-webkit-scrollbar-thumb:hover {
  background: rgba(0, 0, 0, 0.5);
}
.bottomBS h4 {
  margin-bottom: 20px;
}
.bottomBS div {
  margin-bottom: 10px;
}
button {
  appearance: none;
  border: none;
  background: none;
  padding: 3px;
  margin: 0;
  font: inherit;
  color: inherit;
  cursor: pointer;
  text-shadow: 0 1px 4px rgba(0, 0, 0, 0.45);
  min-width: 40px;
}
.topLink {
  appearance: none;
  border: 0;
  background: transparent;
  color: inherit;
  font: inherit;
  cursor: pointer;
  letter-spacing: 0.02em;
  transition:
    opacity 180ms ease,
    transform 180ms ease;
}
.topLink:hover {
  opacity: 0.72;
  transform: translateY(-1px);
}
.topLinkRight {
  font-size: 13px;
}
.menuItem {
  appearance: none;
  border: 0;
  background: transparent;
  color: inherit;
  font: inherit;
  font-size: 18px;
  letter-spacing: 0.02em;
  cursor: pointer;
  text-align: left;
  transition:
    background-color 180ms ease,
    transform 180ms ease;
}
.menuItem:hover {
  background: rgba(255, 255, 255, 0.05);
  transform: translateX(4px);
}
.menuItemMobile {
  padding: 20px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}
@media (prefers-color-scheme: dark) {
  html {
    color-scheme: dark;
  }
}
//===== app/page.module.css =====
.page {
  --background: #fafafa;
  --foreground: #fff;
  --text-primary: #000;
  --text-secondary: #666;
  --button-primary-hover: #383838;
  --button-secondary-hover: #f2f2f2;
  --button-secondary-border: #ebebeb;
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-family: var(--font-geist-sans);
  background-color: var(--background);
  position: "relative";
}
.main {
  display: flex;
  flex: 1;
  width: 100%;
  /* max-width: 800px; */
  flex-direction: column;
  align-items: flex-start;
  justify-content: space-between;
  background-color: var(--foreground);
  /* padding: 120px 60px; */
}
.intro {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  text-align: left;
  gap: 24px;
}
.intro h1 {
  max-width: 320px;
  font-size: 40px;
  font-weight: 600;
  line-height: 48px;
  letter-spacing: -2.4px;
  text-wrap: balance;
  color: var(--text-primary);
}
.intro p {
  max-width: 440px;
  font-size: 18px;
  line-height: 32px;
  text-wrap: balance;
  color: var(--text-secondary);
}
.intro a {
  font-weight: 500;
  color: var(--text-primary);
}
.ctas {
  display: flex;
  flex-direction: row;
  width: 100%;
  max-width: 440px;
  gap: 16px;
  font-size: 14px;
}
.ctas a {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 40px;
  padding: 0 16px;
  border-radius: 128px;
  border: 1px solid transparent;
  transition: 0.2s;
  cursor: pointer;
  width: fit-content;
  font-weight: 500;
}
a.primary {
  background: var(--text-primary);
  color: var(--background);
  gap: 8px;
}
a.secondary {
  border-color: var(--button-secondary-border);
}
/* Enable hover only on non-touch devices */
@media (hover: hover) and (pointer: fine) {
  a.primary:hover {
    background: var(--button-primary-hover);
    border-color: transparent;
  }
  a.secondary:hover {
    background: var(--button-secondary-hover);
    border-color: transparent;
  }
}
@media (max-width: 600px) {
  .main {
    /* padding: 48px 24px; */
  }
  .intro {
    gap: 16px;
  }
  .intro h1 {
    font-size: 32px;
    line-height: 40px;
    letter-spacing: -1.92px;
  }
}
@media (prefers-color-scheme: dark) {
  .logo {
    filter: invert();
  }
  .page {
    --background: #000;
    --foreground: #000;
    --text-primary: #ededed;
    --text-secondary: #999;
    --button-primary-hover: #ccc;
    --button-secondary-hover: #1a1a1a;
    --button-secondary-border: #1a1a1a;
  }
}
//===== vStore/inventoryStore.js =====
"use client";
import { proxy, useSnapshot } from "valtio";
// ----- Default data (seed) -----
const defaultProducts = [
  {
    id: "sabina-dress",
    name: "Sabina Dress",
    src: "https://co.silviatcherassi.com/cdn/shop/files/91_SabinaDress_White__PRESPRING2026_FRONT.jpg?v=1771536063&width=1000",
    price: 2100000,
    variants: [],
    collectionId: null,
  },
  {
    id: "rowan-dress",
    name: "Rowan Dress",
    src: "https://co.silviatcherassi.com/cdn/shop/files/89_RowanDress_White__PRESPRING2026_FRONT.jpg?v=1771535925&width=1000",
    price: 2100000,
    variants: [],
    collectionId: null,
  },
  {
    id: "norma-dress",
    name: "Norma Dress",
    src: "https://co.silviatcherassi.com/cdn/shop/files/80___Norma_Dress___Vanilla___PRE_SPRING_2026_FRONT_4b5ba98e-1241-4ad1-a9e1-05181b9a069e.jpg?v=1757978129&width=1000",
    price: 2100000,
    variants: [],
    collectionId: null,
  },
  {
    id: "naga-dress",
    name: "Naga Dress",
    src: "https://co.silviatcherassi.com/cdn/shop/files/55___Naga_Dress___Tangerine___PRE_SPRING_2026_FRONT.jpg?v=1757883456&width=1000",
    price: 2100000,
    variants: [],
    collectionId: null,
  },
  {
    id: "asher-dress",
    name: "Asher Dress",
    src: null,
    price: 2100000,
    variants: [],
    collectionId: null,
  },
];
const defaultCollections = [
  {
    id: "col1",
    name: "Collection 1",
    href: "/collections/collection-1",
    src: "https://co.silviatcherassi.com/cdn/shop/files/1402-3_1.jpg?v=1775769358&width=1500",
  },
  {
    id: "col2",
    name: "Collection 2",
    href: "/collections/collection-2",
    src: "https://co.silviatcherassi.com/cdn/shop/files/2_f3b3831b-f41c-4f32-8a48-d5b3c045bac4.jpg?v=1775754993&width=1500",
  },
  {
    id: "col3",
    name: "Collection 3",
    href: "/collections/collection-3",
    src: "https://co.silviatcherassi.com/cdn/shop/files/SPRING_2026_-_HERO_IMAGES_13_b2600db3-62f4-4632-b8e2-b433de7b77ee.jpg?v=1775489708&width=1500",
  },
  {
    id: "col4",
    name: "Collection 4",
    href: "/collections/collection-4",
    src: "https://co.silviatcherassi.com/cdn/shop/files/SPRING_2026_-_HERO_IMAGES_19_e3e6e248-ee80-432f-a4be-114ceebf414b.jpg?v=1775489710&width=832",
  },
];
// ----- Load persisted data from localStorage (for dynamic updates) -----
const loadData = () => {
  if (typeof window === "undefined")
    return { products: defaultProducts, collections: defaultCollections };
  const storedProducts = localStorage.getItem("inventory_products");
  const storedCollections = localStorage.getItem("inventory_collections");
  return {
    products: storedProducts ? JSON.parse(storedProducts) : defaultProducts,
    collections: storedCollections
      ? JSON.parse(storedCollections)
      : defaultCollections,
  };
};
const { products: initialProducts, collections: initialCollections } =
  loadData();
// ----- Valtio proxy state -----
const store = proxy({
  products: initialProducts,
  collections: initialCollections,
});
// ----- Persist helper (saves to localStorage after each mutation) -----
const persist = () => {
  if (typeof window !== "undefined") {
    localStorage.setItem("inventory_products", JSON.stringify(store.products));
    localStorage.setItem(
      "inventory_collections",
      JSON.stringify(store.collections),
    );
  }
};
// ----- Actions (mutate the proxy directly) -----
export const inventoryActions = {
  addProduct(product) {
    store.products.push(product);
    persist();
  },
  updateProduct(id, updates) {
    const product = store.products.find((p) => p.id === id);
    if (product) Object.assign(product, updates);
    persist();
  },
  deleteProduct(id) {
    const index = store.products.findIndex((p) => p.id === id);
    if (index !== -1) store.products.splice(index, 1);
    persist();
  },
  assignCollection(productId, collectionId) {
    const product = store.products.find((p) => p.id === productId);
    if (product) product.collectionId = collectionId || null;
    persist();
  },
  addCollection(collection) {
    store.collections.push(collection);
    persist();
  },
  updateCollection(id, updates) {
    const collection = store.collections.find((c) => c.id === id);
    if (collection) Object.assign(collection, updates);
    persist();
  },
  deleteCollection(id) {
    // Remove reference from all products
    store.products.forEach((p) => {
      if (p.collectionId === id) p.collectionId = null;
    });
    const index = store.collections.findIndex((c) => c.id === id);
    if (index !== -1) store.collections.splice(index, 1);
    persist();
  },
};
// ----- Helper to get a single product (reactive if used inside useSnapshot) -----
export const getItemById = (id) =>
  store.products.find((p) => p.id === id) ?? null;
// ----- Custom hook for React components -----
export function useInventory() {
  const snap = useSnapshot(store);
  return {
    products: snap.products,
    collections: snap.collections,
    ...inventoryActions,
    getItemById: (id) => snap.products.find((p) => p.id === id) ?? null,
  };
}
//===== vStore/cartStore.js =====
"use client";
import { proxy, useSnapshot } from "valtio";
// ----- Load cart & migrate old 'id' to '_id' -----
const loadCart = () => {
  if (typeof window === "undefined") return { items: [] };
  const stored = localStorage.getItem("cart_items");
  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      // migrate: copy old id → _id if missing
      return {
        items: parsed.map((item) => ({
          ...item,
          _id: item._id || item.id, // fallback to old id
        })),
      };
    } catch {
      return { items: [] };
    }
  }
  return { items: [] };
};
const { items: initialItems } = loadCart();
const cartState = proxy({ items: initialItems });
const persistCart = () => {
  if (typeof window !== "undefined") {
    localStorage.setItem("cart_items", JSON.stringify(cartState.items));
  }
};
export const cartActions = {
  addItem(product, variant, qty = 1) {
    const existing = cartState.items.find(
      (i) => i._id === product._id && i.variant === variant,
    );
    if (existing) {
      existing.qty += qty;
    } else {
      cartState.items.push({
        _id: product._id, // store only _id
        variant: variant || null,
        price: product.price,
        qty,
      });
    }
    persistCart();
  },
  updateQty(_id, variant, newQty) {
    if (newQty < 1) return;
    const item = cartState.items.find(
      (i) => i._id === _id && i.variant === variant,
    );
    if (item) {
      item.qty = newQty;
      persistCart();
    }
  },
  removeItem(_id, variant) {
    const index = cartState.items.findIndex(
      (i) => i._id === _id && i.variant === variant,
    );
    if (index !== -1) {
      cartState.items.splice(index, 1);
      persistCart();
    }
  },
  clearCart() {
    cartState.items = [];
    persistCart();
  },
};
export function useCart() {
  const snap = useSnapshot(cartState);
  const count = snap.items.reduce((sum, i) => sum + i.qty, 0);
  const subtotal = snap.items.reduce((sum, i) => sum + i.price * i.qty, 0);
  return {
    items: snap.items,
    count,
    subtotal,
    addItem: cartActions.addItem,
    updateQty: cartActions.updateQty,
    removeItem: cartActions.removeItem,
    clearCart: cartActions.clearCart,
  };
}
//===== vStore/CORE/assets.js =====
// vStore/CORE/assets.js (final)
import { proxy, useSnapshot, snapshot } from "valtio";
import axios from "axios";
const state = proxy({
  products: [],
  collections: [],
  loading: false,
  error: null,
});
// Fetch helpers (use generic CORE endpoint)
async function fetchProducts() {
  const { data } = await axios.get("/api/CORE/products");
  return data.response ?? data;
}
async function fetchCollections() {
  const { data } = await axios.get("/api/CORE/collections");
  return data.response ?? data;
}
export async function initAssets() {
  if (state.loading) return;
  state.loading = true;
  state.error = null;
  try {
    const [products, collections] = await Promise.all([
      fetchProducts(),
      fetchCollections(),
    ]);
    state.products = products;
    state.collections = collections;
  } catch (err) {
    state.error = err.message;
    console.error("Failed to load assets:", err);
  } finally {
    state.loading = false;
  }
}
// Generic CRUD (unchanged from earlier)
export async function addAsset(collection, data) {
  try {
    const res = await axios.post(`/api/CORE/${collection}`, data);
    const newDoc = res.data.asset ?? res.data;
    state[collection].push(newDoc);
    return newDoc;
  } catch (err) {
    console.error(`addAsset (${collection}) failed:`, err);
    throw err;
  }
}
export async function updateAsset(collection, id, updates) {
  try {
    await axios.patch(`/api/CORE/${collection}`, { id, data: updates });
    const index = state[collection].findIndex((item) => item._id === id);
    if (index !== -1) {
      state[collection][index] = { ...state[collection][index], ...updates };
    }
  } catch (err) {
    console.error(`updateAsset (${collection}) failed:`, err);
    throw err;
  }
}
export async function deleteAsset(collection, id) {
  if (!collection || !id) throw new Error("collection and id required");
  if (!window.confirm("Are you sure you want to delete this item?")) return;
  try {
    await axios.delete(`/api/CORE/${collection}`, { params: { id } });
    const index = state[collection].findIndex((item) => item._id === id);
    if (index !== -1) state[collection].splice(index, 1);
    return true;
  } catch (err) {
    console.error(`deleteAsset (${collection}) failed:`, err);
    return false;
  }
}
// Domain-specific actions
export const addProduct = (data) => addAsset("products", data);
export const updateProduct = (id, updates) =>
  updateAsset("products", id, updates);
export const deleteProduct = (id) => deleteAsset("products", id);
export const addCollection = (data) => addAsset("collections", data);
export const updateCollection = (id, updates) =>
  updateAsset("collections", id, updates);
export const deleteCollection = (id) => deleteAsset("collections", id);
export const assignCollection = (productId, collectionId) =>
  updateAsset("products", productId, { collectionId });
// Synchronous helpers
export const getAsset = (section, _id) =>
  state[section]?.find((asset) => asset._id == _id) ?? null;
// React hook – SSR safe
export const useAssets = () =>
  typeof window === "object" ? useSnapshot(state) : snapshot(state);
export default state;
//===== lib/mongodb.js =====
// lib/mongodb.js (or lib/api/util/mongodb.js – just keep a single file)
const { MongoClient } = require("mongodb");
const { MONGODB_URI, MONGODB_DB } = process.env;
if (!MONGODB_URI) {
  throw new Error(
    "Please define the MONGODB_URI environment variable inside .env.local",
  );
}
if (!MONGODB_DB) {
  throw new Error(
    "Please define the MONGODB_DB environment variable inside .env.local",
  );
}
/**
 * Global is used here to maintain a cached connection across hot reloads
 * in development. This prevents connections growing exponentially
 * during API Route usage.
 */
let cached = global.mongo;
if (!cached) cached = global.mongo = {};
const connectToDatabase = async () => {
  if (cached.conn) return cached.conn;
  if (!cached.promise) {
    const conn = {};
    cached.promise = MongoClient.connect(MONGODB_URI)
      .then((client) => {
        conn.client = client;
        return client.db(MONGODB_DB);
      })
      .then((db) => {
        conn.db = db;
        cached.conn = conn;
      });
  }
  await cached.promise;
  return cached.conn;
};
module.exports = {
  connectToDatabase,
};
//===== lib/api/models/default.js =====
const { deleteFolderInCollection } = require("../../wasabi");
const { ObjectId } = require("mongodb");
const create = async (collection, data) => {
  const { connectToDatabase } = require("../../mongodb");
  const { db } = await connectToDatabase();
  const res = await db.collection(collection).insertOne(data);
  return res;
};
const getAll = async (collection) => {
  const { connectToDatabase } = require("../../mongodb");
  const { db } = await connectToDatabase();
  return db.collection(collection).find({}).toArray();
};
// Accept a query object (e.g. { phone: "+57..." } or { _id: "..." })
// Maps `phone` => `info.phone` so GET ?phone=... works with nested storage.
const get = async (collection, query = {}) => {
  const { connectToDatabase } = require("../../mongodb");
  const { db } = await connectToDatabase();
  // If query is a string/number (legacy), fall back to return all
  if (!query || typeof query !== "object") {
    return db.collection(collection).find({}).toArray();
  }
  const filter = {};
  // support _id query
  if (query._id) {
    try {
      filter._id = ObjectId(query._id);
    } catch (e) {
      // invalid id string -> no results
      return [];
    }
  }
  // convenience: query ?phone=... -> map to info.phone
  if (query.phone) {
    filter["info.phone"] = query.phone;
  }
  // copy other direct keys (shallow)
  Object.keys(query).forEach((k) => {
    if (k === "_id" || k === "phone") return;
    // handle numeric strings for offset/limit if you later support them
    filter[k] = query[k];
  });
  return db.collection(collection).find(filter).toArray();
};
// remove: accept either id string or { id: '...' } to match route usage
const remove = async (collection, idOrObj, wasabiId = undefined) => {
  const { connectToDatabase } = require("../../mongodb");
  const { db } = await connectToDatabase();
  let _id = idOrObj;
  if (idOrObj && typeof idOrObj === "object" && idOrObj.id) {
    _id = idOrObj.id;
  }
  if (!_id) {
    throw new Error("missing id for remove");
  }
  wasabiId && (await deleteFolderInCollection(collection, wasabiId));
  return db.collection(collection).deleteOne({ _id: ObjectId(_id) });
};
// Patch/update a document by _id. data is the partial object to $set.
const update = async (collection, id, data) => {
  const { connectToDatabase } = require("../../mongodb");
  const { db } = await connectToDatabase();
  if (!id) throw new Error("missing id for update");
  if (!data || Object.keys(data).length === 0)
    throw new Error("missing data for update");
  const res = await db
    .collection(collection)
    .updateOne({ _id: new ObjectId(id) }, { $set: data }, { upsert: false });
  return res;
};
module.exports = {
  create,
  getAll,
  get,
  remove,
  update,
};
//===== lib/api/models/updateAsset.js =====
import { ObjectId } from "mongodb";
import { connectToDatabase } from "../../mongodb";
export async function updateAsset(req, res, collectionName, fields) {
  const asset = req.assetsState[collectionName].find(
    (asset) => asset._id == req.body._id,
  );
  if (req.method === "PUT") {
    try {
      const { db } = await connectToDatabase();
      const issuer = req.session.user;
      const edition = {
        utc: new Date(),
        by: new ObjectId(issuer._id),
      };
      const result = await db.collection(collectionName).updateOne(
        {
          _id: ObjectId(req.body._id),
        },
        {
          $set: fields,
          $push: {
            edition,
          },
        },
      );
      if (!result.acknowledged) {
        return res.status(400).json({
          status: "failure",
          message: "Update operation was not acknowledged",
        });
      } else {
        for (const field in fields) {
          asset[field] = req.body[field];
        }
        !asset.edition && (asset.edition = []);
        asset.edition.push(JSON.parse(JSON.stringify(edition)));
        res.status(200).json({
          status: "success",
          data: result,
        });
      }
    } catch (error) {
      res.status(500).json({
        status: "failure",
        message: "An error occurred while updating the asset",
        error: error.message,
      });
    }
  } else {
    res.status(405).end(`Method ${req.method} Not Allowed`);
  }
  asset.editing = false;
}
//===== lib/wasabi.js =====
// A good reference for V3 of S3 code examples is https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javascriptv3/example_code/s3/src
// and https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javascriptv3/example_code/s3/src
// FS for file uploading
// const fs = require("fs");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner"); // npm install @aws-sdk/s3-request-presigner first, https://www.npmjs.com/package/@aws-sdk/s3-request-presigner
const REGION = process.env.AWS_REGION; //https://wasabi-support.zendesk.com/hc/en-us/articles/360015106031-What-are-the-service-URLs-for-Wasabi-s-different-regions-
//https://github.com/annabelle/wasabi-aws-sdk-js-v3-demo/blob/main/wasabi_S3_JDK_V3_examples.js
const {
  S3Client,
  PutObjectCommand,
  CreateBucketCommand,
  ListBucketsCommand,
  ListObjectsCommand,
  GetObjectCommand,
  DeleteObjectCommand,
} = require("@aws-sdk/client-s3");
// const { sign } = require("crypto");
const s3Client = new S3Client({
  region: REGION,
  endpoint: `https://s3.${REGION}.wasabisys.com`,
  signatureVersion: "v4",
  credentialDefaultProvider: () => ({
    accessKeyId: process.env.AWS_ACCESS_KEY,
    secretAccessKey: process.env.AWS_SECRET_KEY,
  }),
});
// Set the bucket parameters.
const bucketParams = { Bucket: "imptech" };
// const file = "upload_me.txt"; // Path to and name of object. For example '../myFiles/index.js'.
//const file = "exampleUploadPDF.pdf";
// const fileStream= fs.createReadStream(file);
// Set the parameters for streaming object (object uploaded from file system)
// let uploadStreamingObjectParams = {
//   // bucket name
//   Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
//   // Add the required 'Key' parameter using the 'path' module.
//   Key: path.basename(file),
//   // Add the required 'Body' parameter, this is actual file content
//   Body: fileStream,
// };
//set the parameters for uploading internal application content (not uploaded)
// let internalObjectContent =
//   "<strong> I'm html and I'm uploaded, could have done a .txt <u>instead</u> here too for example </strong>";
let internalObjectName = "setcontentInternalAppContentExample.html";
//let internalObjectName = "upload_me.txt"
// Create the S3 bucket.
async function makeBucket(bucketParams) {
  try {
    const data = await s3Client.send(new CreateBucketCommand(bucketParams));
    console.log("Success", data);
    return data; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
}
// returns an array of bucket objects with name and creation Date
async function listBuckets() {
  try {
    const data = await s3Client.send(new ListBucketsCommand({}));
    console.log("Success", data);
    return data; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
}
//upload an object from a file system or internally from app, depending on parameters
async function putObject(uploadParams) {
  try {
    const data = await s3Client.send(new PutObjectCommand(uploadParams));
    console.log("Success", data);
    return data; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
}
async function listObjectsCommand(bucketParams) {
  try {
    const data = await s3Client.send(new ListObjectsCommand(bucketParams));
    console.log("Success", data);
    return data; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
}
async function getObjectCommand(bucketParams) {
  try {
    // Create a helper function to convert a ReadableStream to a string.
    // TODO: Production apps may want a CDN as a good way to avoid reading large amounts from memeory
    const streamToString = (stream) =>
      new Promise((resolve, reject) => {
        const chunks = [];
        stream.on("data", (chunk) => chunks.push(chunk));
        stream.on("error", reject);
        stream.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
      });
    // Get the object} from the Amazon S3 bucket. It is returned as a ReadableStream.
    const data = await s3Client.send(new GetObjectCommand(bucketParams));
    const bodyContents = await streamToString(data.Body);
    console.log(bodyContents);
    return bodyContents;
  } catch (err) {
    console.log("Error", err);
  }
}
async function deleteObjectCommand(bucketParams) {
  try {
    const data = await s3Client.send(new DeleteObjectCommand(bucketParams));
    console.log("Success", data);
    return data; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
}
async function deleteFolderInCollection(collection, id) {
  const params = {
    Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
    Prefix: `${collection}/${id}`,
  };
  console.log("id: ", id);
  try {
    const data = await s3Client.send(new ListObjectsCommand(params));
    data.Contents &&
      (await Promise.all(
        data.Contents?.map((media) =>
          s3Client.send(
            new DeleteObjectCommand({
              Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
              Key: media.Key,
            }),
          ),
        ),
      ));
    // const data = await s3Client.send(new DeleteObjectCommand(params));
    console.log("Success", data);
    return data; // For unit tests.
  } catch (err) {
    console.log("Error", err);
  }
}
async function deleteList(list) {
  try {
    await Promise.all(
      list.map((location) =>
        s3Client.send(
          new DeleteObjectCommand({
            Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
            Key: location,
          }),
        ),
      ),
    );
    // const data = await s3Client.send(new DeleteObjectCommand(params));
  } catch (err) {
    console.log("Error", err);
  }
}
async function getSignedURL(key) {
  const params = {
    Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
    Key: key,
    ContentType: "image/jpeg",
  };
  try {
    // Create the command.
    const command = new GetObjectCommand(params);
    // Create the presigned URL.
    const signedUrl = await getSignedUrl(s3Client, command, {
      expiresIn: 3600 * 24,
    });
    // console.log(
    //   `\nGetting "${bucketParams.Key}" using signedUrl with body "${bucketParams.Body}" in v3`
    // );
    //
    return signedUrl;
    // console.log(signedUrl);
    /*
    // we aren't actually trying to get the content, just want the url
    const response = await fetch(signedUrl);
      nsole.log(
      `\nResponse returned by signed URL: ${await response.text()}\n`
    );
    */
  } catch (err) {
    console.log("Error creating presigned URL", err);
  }
}
async function getPreSignedURL(key) {
  try {
    const params = {
      Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
      Key: key,
      ContentType: "image/jpeg",
    };
    return await getSignedUrl(s3Client, new PutObjectCommand(params), {
      expiresIn: 3600, // The URL will expire in 1 hour
      // Set the HTTP method to PUT to allow upload
      method: "PUT",
    });
  } catch (err) {
    console.log("Error creating presigned URL", err);
  }
}
async function uploadFile(key, file) {
  console.log("THE key", key);
  console.log("THE file", file);
  // const internalObjectContent = console.log("bucket", bucketParams.Bucket);
  let uploadInternalObjectParams = {
    // bucket name
    Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
    // Add the required 'Key' parameter using the 'path' module.
    Key: key,
    // Add the required 'Body' parameter, this is actual file content
    Body: file,
    ACL: "public-read",
    ContentType: "image/jpeg",
    // ContentType: "text/html", //'text/plain' for .txt
  };
  let getObjectParams = {
    // bucket name
    Bucket: bucketParams.Bucket, //Bucket: "currentj-ihasabucket",
    // Add the required 'Key' parameter using the 'path' module.
    Key: key,
  };
  const result = await putObject(uploadInternalObjectParams);
  console.log("test img:", result);
  return await getSignedURL(getObjectParams);
}
//uncomment the code below depending on what you want to see an example of
//makeBucket(bucketParams);
// listBuckets();
//putObject(uploadStreamingObjectParams);
//putObject(uploadInternalObjectParams); //change to inline
//listObjectsCommand(bucketParams);
//getObjectCommand(getObjectParams);
//deleteObjectCommand(getObjectParams);
//getSignedURL(getObjectParams);
//if want to do an upload and directly after get the signed params then need to make sure signing is done after object is put
//putObject(uploadInternalObjectParams).then(() => getSignedURL(getObjectParams));
//
//
module.exports = {
  deleteList,
  listBuckets,
  uploadFile,
  getPreSignedURL,
  getSignedURL,
  deleteFolderInCollection,
};
