//===== app/layout.js =====
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Top from "../components/Top.js";
import Bottom from "../components/Bottom.js";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Top />
        {children}
        <Bottom />
      </body>
    </html>
  );
}
//===== app/collections/[slug]/page.js =====
"use client";
import { useParams } from "next/navigation";
import Link from "next/link";
const mockProducts = [
  { id: 1, name: "Vestido Alma", price: "$2.100.000" },
  { id: 2, name: "Blusa Cielo", price: "$980.000" },
  { id: 3, name: "Falda Luna", price: "$1.200.000" },
  { id: 4, name: "Vestido Sol", price: "$2.400.000" },
  { id: 5, name: "Top Brisa", price: "$750.000" },
  { id: 6, name: "Pantalón Niebla", price: "$1.100.000" },
  { id: 7, name: "Vestido Mar", price: "$1.900.000" },
  { id: 8, name: "Conjunto Río", price: "$2.800.000" },
];
export default function CollectionPage() {
  const { slug } = useParams();
  const title = slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
  return (
    <>
      <h4
        style={{
          position: "sticky",
          top: 100,
          zIndex: 10,
          textAlign: "center",
          textTransform: "uppercase",
          fontWeight: 400,
          background: "var(--background)",
          marginBottom: 2,
        }}
      >
        {title}
      </h4>
      <div className="mosaicGrid">
        {mockProducts.map((p) => (
          <Link key={p.id} href={`/prod/${p.id}`} className="mosaicCard">
            <div className="mosaicImg" />
            <div className="mosaicInfo">
              <span className="mosaicName">{p.name}</span>
              <span className="mosaicPrice">{p.price} COP</span>
            </div>
          </Link>
        ))}
      </div>
      <style jsx global>{`
        .mosaicGrid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 2px;
        }
        @media (max-width: 900px) {
          .mosaicGrid {
            grid-template-columns: repeat(2, 1fr);
          }
        }
        @media (max-width: 500px) {
          .mosaicGrid {
            grid-template-columns: 1fr;
          }
        }
        .mosaicCard {
          display: flex;
          flex-direction: column;
          text-decoration: none;
          color: inherit;
          cursor: pointer;
        }
        .mosaicImg {
          width: 100%;
          aspect-ratio: 3 / 4;
          background: #e8e4df;
          overflow: hidden;
          transition: opacity 300ms ease;
        }
        .mosaicCard:hover .mosaicImg {
          opacity: 0.85;
        }
        .mosaicInfo {
          display: flex;
          flex-direction: column;
          gap: 4px;
          padding: 12px 4px;
        }
        .mosaicName {
          font-size: 13px;
          letter-spacing: 0.06em;
          text-transform: uppercase;
        }
        .mosaicPrice {
          font-size: 12px;
          color: #666;
        }
      `}</style>
    </>
  );
}
//===== components/Top.js =====
"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
const leftItems = ["Comprar", "Colecciones", "Novias", "Más"];
const rightItems = ["Buscar", "Carrito"];
export default function Top() {
  const router = useRouter();
  const topbarRef = useRef(null);
  const measureRef = useRef(null);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [topbarHeight, setTopbarHeight] = useState(0);
  const [canInlineNav, setCanInlineNav] = useState(true);
  useEffect(() => {
    const updateLayout = () => {
      if (topbarRef.current) {
        setTopbarHeight(topbarRef.current.offsetHeight);
      }
      if (measureRef.current && topbarRef.current) {
        const available = topbarRef.current.clientWidth;
        const needed = measureRef.current.scrollWidth + 24;
        setCanInlineNav(available >= needed);
      }
    };
    updateLayout();
    const ro = new ResizeObserver(updateLayout);
    if (topbarRef.current) ro.observe(topbarRef.current);
    window.addEventListener("resize", updateLayout);
    return () => {
      ro.disconnect();
      window.removeEventListener("resize", updateLayout);
    };
  }, []);
  useEffect(() => {
    if (canInlineNav) {
      setIsMenuOpen(false);
    }
  }, [canInlineNav]);
  useEffect(() => {
    const handleScroll = () => {
      if (!canInlineNav && window.scrollY > 80) {
        setIsMenuOpen(false);
      }
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, [canInlineNav]);
  return (
    <>
      <div
        ref={topbarRef}
        style={{
          position: "sticky",
          top: 0,
          zIndex: 2000,
          width: "100%",
          background: "rgba(0,0,0,0.72)",
          backdropFilter: "blur(14px)",
          color: "#fff",
          boxShadow: "0 4px 24px rgba(0,0,0,0.35)",
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr auto 1fr",
            alignItems: "center",
            padding: "15px 20px",
            gap: 20,
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 22,
              minWidth: 0,
              overflow: "hidden",
              whiteSpace: "nowrap",
            }}
          >
            {canInlineNav ? (
              leftItems.map((item) => (
                <button key={item} className="topLink" type="button">
                  {item}
                </button>
              ))
            ) : (
              <button
                className="topLink"
                type="button"
                onClick={() => setIsMenuOpen((v) => !v)}
              >
                Menu
              </button>
            )}
          </div>
          <b
            style={{
              textAlign: "center",
              cursor: "pointer",
              letterSpacing: "0.18em",
              fontWeight: 700,
              whiteSpace: "nowrap",
              textShadow: "0 1px 4px rgba(0,0,0,0.45)",
            }}
            onClick={() => router.push("/")}
          >
            ASHERALEPH
          </b>
          <div
            style={{
              display: "flex",
              justifyContent: "flex-end",
              alignItems: "center",
              gap: 18,
              minWidth: 0,
              overflow: "hidden",
              whiteSpace: "nowrap",
            }}
          >
            {rightItems.map((item) => (
              <button key={item} className="topLink" type="button">
                {item}
              </button>
            ))}
          </div>
        </div>
        <div
          ref={measureRef}
          aria-hidden="true"
          style={{
            position: "absolute",
            visibility: "hidden",
            pointerEvents: "none",
            left: -99999,
            top: -99999,
            whiteSpace: "nowrap",
            display: "flex",
            alignItems: "center",
            gap: 18,
            padding: "15px 20px",
          }}
        >
          {leftItems.map((item) => (
            <span key={item} style={{ padding: "6px 0" }}>
              {item}
            </span>
          ))}
          <span
            style={{
              letterSpacing: "0.18em",
              fontWeight: 700,
            }}
          >
            ASHERALEPH
          </span>
          {rightItems.map((item) => (
            <span key={item} style={{ padding: "6px 0" }}>
              {item}
            </span>
          ))}
        </div>
      </div>
      {!canInlineNav && (
        <div
          style={{
            position: "fixed",
            top: Math.max(0, topbarHeight - 1),
            left: 0,
            right: 0,
            zIndex: 1500,
            background: "rgba(0,0,0,0.94)",
            backdropFilter: "blur(18px)",
            color: "#fff",
            overflow: "hidden",
            opacity: isMenuOpen ? 1 : 0,
            transform: isMenuOpen ? "translateY(0px)" : "translateY(-12px)",
            pointerEvents: isMenuOpen ? "auto" : "none",
            transition: "opacity 0.28s ease, transform 0.28s ease",
            boxShadow: "0 14px 40px rgba(0,0,0,0.45)",
          }}
        >
          <div style={{ display: "flex", flexDirection: "column" }}>
            {leftItems.map((item) => (
              <button
                key={item}
                type="button"
                className="menuItem menuItemMobile"
                onClick={() => setIsMenuOpen(false)}
              >
                {item}
              </button>
            ))}
          </div>
        </div>
      )}
      <style jsx global>{`
        .topLink {
          appearance: none;
          border: 0;
          background: transparent;
          color: inherit;
          font: inherit;
          font-size: 14px;
          cursor: pointer;
          padding: 6px 0;
          letter-spacing: 0.02em;
          transition:
            opacity 180ms ease,
            transform 180ms ease;
        }
        .topLink:hover {
          opacity: 0.72;
          transform: translateY(-1px);
        }
        .menuItem {
          appearance: none;
          border: 0;
          background: transparent;
          color: inherit;
          font: inherit;
          font-size: 18px;
          letter-spacing: 0.02em;
          cursor: pointer;
          text-align: left;
          transition:
            background-color 180ms ease,
            transform 180ms ease;
        }
        .menuItem:hover {
          background: rgba(255, 255, 255, 0.05);
          transform: translateX(4px);
        }
        .menuItemMobile {
          padding: 20px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.08);
        }
      `}</style>
    </>
  );
}
//===== app/globals.css =====
:root {
  --background: #ffffff;
  --foreground: #171717;
}
@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}
html {
  height: 100%;
}
html,
body {
  max-width: 100vw;
}
body {
  min-height: 100%;
  display: flex;
  flex-direction: column;
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
}
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}
a {
  color: inherit;
  text-decoration: none;
}
.image-container {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(550px, 1fr));
  width: 100vw;
}
.image-container img {
  width: 100%;
  max-width: 100vw;
  height: 100%;
  object-fit: cover;
}
.carousel-img {
  /* opacity: 0.6; */
}
.carousel-img-wrapper {
  overflow: hidden;
  max-height: 300px;
  min-height: 300px;
}
.carousel-img-wrapper img:hover {
  transform: scale(1.62);
}
.detalles {
  border-top: 1px solid silver;
  margin-top: 20px;
}
.detalles div {
  padding: 20px;
  border-bottom: 1px solid silver;
}
.detalles div:hover {
  background: silver;
  color: black;
}
.scroll {
  overflow-x: auto;
  scrollbar-width: thin;
  /* Firefox */
  scrollbar-color: rgba(100, 100, 100, 0.3) transparent;
}
.scroll::-webkit-scrollbar {
  height: 6px;
  /* thin horizontal bar */
}
.scroll::-webkit-scrollbar-track {
  background: transparent;
  /* invisible track */
}
.scroll::-webkit-scrollbar-thumb {
  background: rgba(0, 0, 0, 0.3);
  border-radius: 999px;
}
.scroll::-webkit-scrollbar-thumb:hover {
  background: rgba(0, 0, 0, 0.5);
}
.bottomBS h4 {
  margin-bottom: 20px;
}
.bottomBS div {
  margin-bottom: 10px;
}
button {
  appearance: none;
  border: none;
  background: none;
  padding: 3px;
  margin: 0;
  font: inherit;
  color: inherit;
  cursor: pointer;
  text-shadow: 0 1px 4px rgba(0, 0, 0, 0.45);
  min-width: 40px;
}
.topLink {
  appearance: none;
  border: 0;
  background: transparent;
  color: inherit;
  font: inherit;
  cursor: pointer;
  letter-spacing: 0.02em;
  transition:
    opacity 180ms ease,
    transform 180ms ease;
}
.topLink:hover {
  opacity: 0.72;
  transform: translateY(-1px);
}
.topLinkRight {
  font-size: 13px;
}
.menuItem {
  appearance: none;
  border: 0;
  background: transparent;
  color: inherit;
  font: inherit;
  font-size: 18px;
  letter-spacing: 0.02em;
  cursor: pointer;
  text-align: left;
  transition:
    background-color 180ms ease,
    transform 180ms ease;
}
.menuItem:hover {
  background: rgba(255, 255, 255, 0.05);
  transform: translateX(4px);
}
.menuItemMobile {
  padding: 20px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}
@media (prefers-color-scheme: dark) {
  html {
    color-scheme: dark;
  }
}
//===== app/page.module.css =====
.page {
  --background: #fafafa;
  --foreground: #fff;
  --text-primary: #000;
  --text-secondary: #666;
  --button-primary-hover: #383838;
  --button-secondary-hover: #f2f2f2;
  --button-secondary-border: #ebebeb;
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-family: var(--font-geist-sans);
  background-color: var(--background);
  position: "relative";
}
.main {
  display: flex;
  flex: 1;
  width: 100%;
  /* max-width: 800px; */
  flex-direction: column;
  align-items: flex-start;
  justify-content: space-between;
  background-color: var(--foreground);
  /* padding: 120px 60px; */
}
.intro {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  text-align: left;
  gap: 24px;
}
.intro h1 {
  max-width: 320px;
  font-size: 40px;
  font-weight: 600;
  line-height: 48px;
  letter-spacing: -2.4px;
  text-wrap: balance;
  color: var(--text-primary);
}
.intro p {
  max-width: 440px;
  font-size: 18px;
  line-height: 32px;
  text-wrap: balance;
  color: var(--text-secondary);
}
.intro a {
  font-weight: 500;
  color: var(--text-primary);
}
.ctas {
  display: flex;
  flex-direction: row;
  width: 100%;
  max-width: 440px;
  gap: 16px;
  font-size: 14px;
}
.ctas a {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 40px;
  padding: 0 16px;
  border-radius: 128px;
  border: 1px solid transparent;
  transition: 0.2s;
  cursor: pointer;
  width: fit-content;
  font-weight: 500;
}
a.primary {
  background: var(--text-primary);
  color: var(--background);
  gap: 8px;
}
a.secondary {
  border-color: var(--button-secondary-border);
}
/* Enable hover only on non-touch devices */
@media (hover: hover) and (pointer: fine) {
  a.primary:hover {
    background: var(--button-primary-hover);
    border-color: transparent;
  }
  a.secondary:hover {
    background: var(--button-secondary-hover);
    border-color: transparent;
  }
}
@media (max-width: 600px) {
  .main {
    /* padding: 48px 24px; */
  }
  .intro {
    gap: 16px;
  }
  .intro h1 {
    font-size: 32px;
    line-height: 40px;
    letter-spacing: -1.92px;
  }
}
@media (prefers-color-scheme: dark) {
  .logo {
    filter: invert();
  }
  .page {
    --background: #000;
    --foreground: #000;
    --text-primary: #ededed;
    --text-secondary: #999;
    --button-primary-hover: #ccc;
    --button-secondary-hover: #1a1a1a;
    --button-secondary-border: #1a1a1a;
  }
}
